#pragma once

#define TAPPING_TERM 250
#define QUICK_TAP_TERM 120

#define DYNAMIC_TAPPING_TERM_INCREMENT 10

#define TAPPING_TERM_PER_KEY
#define TAPPING_TERM_FAST 150

#define DYNAMIC_KEYMAP_LAYER_COUNT 5
